# Operations

In [3]:
import numpy as np

In [6]:
newArray = np.random.randint(0,100,25)

In [7]:
newArray

array([34,  2, 45, 50, 68, 85, 58, 54, 45,  5, 45, 61, 89, 39,  3, 46, 37,
       23, 59, 59, 36, 61,  6, 57,  4])

In [8]:
newArray > 30 # 30'dan büyük sayıları boolean olarak döndürüyor.

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True, False,  True, False])

In [9]:
resultArray = newArray > 30

In [10]:
resultArray

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True, False,  True, False])

In [11]:
newArray

array([34,  2, 45, 50, 68, 85, 58, 54, 45,  5, 45, 61, 89, 39,  3, 46, 37,
       23, 59, 59, 36, 61,  6, 57,  4])

In [12]:
newArray[resultArray] # True olan değerleri getirmiş olduk.

array([34, 45, 50, 68, 85, 58, 54, 45, 45, 61, 89, 39, 46, 37, 59, 59, 36,
       61, 57])

In [13]:
Array2 = np.arange(0,24)

In [14]:
Array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
Array2 + Array2 # 2 dizi topladık.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [17]:
Array2 * Array2 # 2 diziyi çarptık

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [18]:
Array2 - Array2 # 2 diziyi birbirinden çıkardık

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [19]:
Array2 / Array2 # 2 diziyi birbirine böldük fakat 0/0 tanımsız ama hata almıyoruz sadece uyarı.

C:\Users\kaann\AppData\Local\Temp\ipykernel_21224\3674971879.py:1: RuntimeWarning: invalid value encountered in divide
  Array2 / Array2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [25]:
newArray2 = Array2[1:]

In [27]:
newArray2 / newArray2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [28]:
np.sqrt(Array2) # karekök aldık.

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [30]:
print(f"{np.max(Array2)},{np.min(Array2)}") # Max , Min değerleri.

23,0
