#  Easy

In [9]:
import numpy as np

In [143]:
# 0–9 arası bir array oluştur.
Array1 = np.arange(0,10)
print(Array1)

[0 1 2 3 4 5 6 7 8 9]


In [144]:
# 10 elemanlı bir rastgele integer array üret (0-50 arası).
randomArray = np.random.randint(0,51,10)
print(randomArray)

[17  2 47 11 17 22  1 45 46 25]


In [145]:
# Bu array’in en küçük, en büyük, ortalama, standart sapma değerlerini bul.
print(randomArray.min())
print(randomArray.max())
print(randomArray.mean())
print(randomArray.std())

1
47
23.3
16.535114151405185


In [14]:
# 0 ile 5 arasında 20 eşit sayı üret.
Array2 = np.linspace(0,5,20)
print(Array2)
# np.linspace(0, 5, 20, endpoint=False) şeklinde 5'i dahil etmeyebiliriz. Defaul olarak endpoint = True

[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]


In [148]:
#3x3 boyutunda identity matrix oluştur
identityMatrix = np.eye(3)
print(identityMatrix)
int_identity_Matrix = np.eye(3, dtype = int)
print("")
print(int_identity_Matrix) # şeklinde integer olarakta alabilirz.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# Mid

In [153]:
# 5x5 boyutunda rastgele matrix üret → köşegenini al.
Array_5 = np.random.randint(0,100,25)
Array_5 = Array_5.reshape(5,5)
print(Array_5)
diag_Array_5 = Array_5.diagonal()
print("")
print(diag_Array_5)
print("")
diag_Array_6 = Array_5[np.arange(5), np.arange(5)] # alternatif olarak bu kullanılabilir
print(diag_Array_6)

[[20 21 61 12 75]
 [98 76 18 78  5]
 [77 47 54 21 78]
 [96  5 44 29 97]
 [79 86 80 22 44]]

[20 76 54 29 44]

[20 76 54 29 44]


In [157]:
# 0,25 arasındaki sayılardan 5x5 matris üret 2. satırı seç, 1. sütunu seç, 3x3’lük ortadaki matrisi al
arr = np.arange(25).reshape(5,5)
print(f"Matrix\n\n{arr},\n\n2. satır = {arr[1]},\n\n1. sütun = {arr[:,0]},\n\n3x3 ortadaki matris =\n\n{arr[1:4,1:4]}")

Matrix

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]],

2. satır = [5 6 7 8 9],

1. sütun = [ 0  5 10 15 20],

3x3 ortadaki matris =

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


In [168]:
# 1D array’den sadece çift sayıları seç (boolean mask ile).
arr_2 = np.random.randint(0,100,10)
print(arr_2)
even_arr_2 = arr_2[arr_2 % 2 == 0]
print(even_arr_2)

[68 31 19 35 39 47 14 74 11 40]
[68 14 74 40]


In [159]:
# 0-10 arası array üretip fancy indexingle 4 değer seç
fancy_arr = np.arange(0,10)
print(fancy_arr)
print(fancy_arr[[1,3,5,7]])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [174]:
# 10 elemanlı rastgele bir array üret, ascending sırala.
random_array = np.random.randint(0,100,10)
print(random_array)
print(np.sort(random_array)) # np.sort() → yeni sıralanmış kopya döndürür.
print(random_array)
random_array.sort() # Eğer array’i yerinde sıralamak istersek bu şekilde yapmalıyız
print(random_array)
print(random_array)

[92 30 59 91 10 80 68 18 54 30]
[10 18 30 30 54 59 68 80 91 92]
[92 30 59 91 10 80 68 18 54 30]
[10 18 30 30 54 59 68 80 91 92]
[10 18 30 30 54 59 68 80 91 92]


# Hard

In [176]:
# 3x3’lük iki rastgele array oluştur
rand_arr = np.random.randint(0,100,9).reshape(3,3)
print(rand_arr)
print("")
print(np.random.randint(0,100,(3,3))) # Farklı bir yaklaşımşa bu şekilde reshape olmadan oluşturabiliriz daha doğru bu.

[[24 72 31]
 [ 2 11 86]
 [42 99  7]]

[[ 9 10 41]
 [11 31 29]
 [35 42  6]]


In [187]:
# 4x4 rastgele matris oluştur
# Aynı matrisin tersini al.
# Matrisin her sütununun ortalamasını bul.
rand_arr_4 = np.random.randint(0,10,16).reshape(4,4)
print(rand_arr_4)
from numpy.linalg import inv
inv_arr = inv(rand_arr_4)
print("")
print(inv_arr)
print("")
print(f"Sütun ortalamları = {rand_arr_4.mean(axis=0)}")
print(f"Satır ortalamları = {rand_arr_4.mean(axis=1)}")

rows , cols = rand_arr_4.shape

row_means = []
col_means = []

for i in range(0,rows):
    sum_rows = 0
    for j in range(0,cols):
        sum_rows += rand_arr_4[i,j]
    row_means.append(sum_rows/cols)

for j in range(cols):                 
    sum_cols = 0
    for i in range(rows):             
        sum_cols += rand_arr_4[i, j]
    col_means.append(sum_cols / rows)      
print("")
print("Sütun ortalamaları:", col_means)
print("Satır ortalamaları:", row_means) # Bu şekilde for yaklaşımıylada bulabiliriz, satır ve sütun mean'leri.

[[1 2 0 9]
 [4 2 2 8]
 [7 9 5 9]
 [8 7 8 8]]

[[-0.44583333  0.56041667  0.1625     -0.24166667]
 [ 0.06666667 -0.23333333  0.2        -0.06666667]
 [ 0.24166667 -0.34583333 -0.275       0.38333333]
 [ 0.14583333 -0.01041667 -0.0625      0.04166667]]

Sütun ortalamları = [5.   5.   3.75 8.5 ]
Satır ortalamları = [3.   4.   7.5  7.75]

Sütun ortalamaları: [5.0, 5.0, 3.75, 8.5]
Satır ortalamaları: [3.0, 4.0, 7.5, 7.75]


In [142]:
# 2 boyutlu array’de hangi elemanların > 10 olduğunu True/False olarak göster (boolean mask)
list1 = [[1,2],[3,14]]
arr_2d = np.array(list1)
print(arr_2d)
print(arr_2d > 10)

[[ 1  2]
 [ 3 14]]
[[False False]
 [False  True]]
