In [1]:
import numpy as np

In [2]:
myArray = np.arange(0,15)

In [3]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
myArray[5]

5

In [5]:
myArray[3:7]

array([3, 4, 5, 6])

In [6]:
myArray[3:7] = -2 # bu işlem direkt myArray içindekileri değiştirir ayrı bir dizi oluşturmaz.

In [7]:
myArray

array([ 0,  1,  2, -2, -2, -2, -2,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
anotherArray = np.arange(24) # 0,24 arası oluturur. (0,24) ile aynı mantık.

In [11]:
anotherArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
slicingArray = anotherArray[3:9]

In [13]:
slicingArray

array([3, 4, 5, 6, 7, 8])

In [14]:
anotherArray # şu an bunda bir değişiklik yapmadık

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
slicingArray[:] = 70

In [16]:
slicingArray

array([70, 70, 70, 70, 70, 70])

In [17]:
anotherArray # Eğer slicingArray'da değişiklik yaparsak bu main Array'imizide etkiliyor.

array([ 0,  1,  2, 70, 70, 70, 70, 70, 70,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
anotherArray_2 = np.arange(24)

In [19]:
anotherArray_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
anotherArray_2_copy = anotherArray_2.copy()

In [21]:
anotherArray_2_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
anotherArray_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
anotherArray_2_slicing = anotherArray_2_copy[3:8]

In [25]:
anotherArray_2_slicing[:] = 100

In [26]:
anotherArray_2_slicing

array([100, 100, 100, 100, 100])

In [27]:
anotherArray_2_copy

array([  0,   1,   2, 100, 100, 100, 100, 100,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [28]:
anotherArray_2 # Eğer main Arrayde değişiklik olmasın istiyorsak copy fonksiyonunu kullanıcağız.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])