In [1]:
import numpy as np

## Numpy Arrays

In [2]:
myList = [20, 30, 40]

In [3]:
type(myList)

list

In [4]:
np.array(myList)

array([20, 30, 40])

In [6]:
type(np.array(myList))

numpy.ndarray

In [7]:
matrixList = [[10,20,30], [20,30,40], [30,40,50]]

In [8]:
type(matrixList)

list

In [9]:
matrixList[1] # eski özellikleri hatırlamak adına

[20, 30, 40]

In [10]:
matrixList[0][2] # eski özellikleri hatırlamak adına

30

In [11]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [13]:
type(np.array(matrixList))

numpy.ndarray

## arange

In [14]:
list(range(0,10)) # eski özellikleri hatırlamak adına

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
np.arange(0,10) # Yukarıdaki işlemin aynısı (sadece liste yerine numpy dizisi oluşturuyor.)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros 

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((2,2)) # 0 matrisi oluşturmak için

array([[0., 0.],
       [0., 0.]])

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace

In [28]:
np.linspace(0,10,3) # 0 ile 10 arasında 3 sayı yazdırıyoruz eşit aralıklarla.

array([ 0.,  5., 10.])

## eye

In [31]:
np.eye(4) # Identity matrix oluşturur.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random

In [33]:
np.random.randn(5) # 5 rastgele sayı üretir

array([ 0.02459067, -0.5081715 , -1.53757671,  0.2569293 , -0.88409181])

In [34]:
np.random.randn(5,5) # 5x5 matris rastgele sayılarla üretir.

array([[-0.26888118, -1.51071848,  0.60527143,  0.21754177, -0.66478453],
       [ 1.94705866, -0.40364725, -0.81382529,  0.17226833,  0.46992697],
       [-0.10794929, -0.57283791, -1.62273755, -0.69435258, -0.49038873],
       [ 2.8797649 , -1.52701977,  1.4144598 , -1.58251502,  1.2689107 ],
       [ 0.23561418,  0.36342728, -0.15424739, -0.50680045, -0.86114426]])

In [51]:
np.random.randint(1,10) # 0 ile 10 arası (10 dahil değil) rastgele integer döndürür.

7

In [52]:
np.random.randint(1,10,5) # 1 ile 10 arası 5 tane integer.

array([5, 4, 8, 6, 9])

In [53]:
myNumpyArray = np.arange(30)

In [54]:
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [58]:
myRandomArray = np.random.randint(0,300,20)

In [59]:
myRandomArray

array([  7,  56,  54, 294, 157, 186, 182, 175, 273,  84, 290,  49, 182,
       113, 151,  84,  28, 284, 249, 227])

## numpay array method

In [65]:
myNumpyArray.reshape(6,5) # Eğer içindeki sayıyla boyut tutmazsa hata alırız.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [66]:
myNumpyArray.max() # Array'deki max değeri bulur

29

In [67]:
myRandomArray.max()

294

In [69]:
myRandomArray.min()# Array'deki min değeri bulur

7

In [70]:
myRandomArray.argmax() # Maximimum değerin indexi.

3

In [71]:
myRandomArray.argmin() # Min değerin indexi.

0

In [73]:
reshapeArray = myNumpyArray.reshape(6,5) 
# Eğer bunu bir değişkene atamazsak sadece o satırlık değiştiriyor eski hali aynı kalıyor.

In [74]:
reshapeArray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [75]:
reshapeArray.shape # Boyutunu öğrenmek için kullanabiliriz. Fonksiyon değil bir attribute parantez kullanmıyoruz.

(6, 5)