# Matrix

In [1]:
import numpy as np

In [2]:
myList = [[10,20,30],[15,25,35],[40,50,60]]

In [3]:
matrixArray = np.array(myList)

In [4]:
matrixArray # np.array() ile listeyi matrise çevirimiş olduk.

array([[10, 20, 30],
       [15, 25, 35],
       [40, 50, 60]])

In [5]:
matrixArray[0] # 0. indeksli eleman

array([10, 20, 30])

In [6]:
matrixArray[1][2] # indeksler 0 ile başladığı için 2. satır 3. sütuna denk geliyor.

35

In [7]:
matrixArray[1,2] # Aslında bu yukarıdaki matrixArray[1][2] ile eşdeğer.

35

In [9]:
matrixArray[0:,2] # Slicingi bu şekilde yapabiliyoruz. Yani 1. satır, 2. satır ve 3. satırın 3. sütunlarını getiriyor.

array([30, 35, 60])

In [10]:
matrixArray[0,0:] # Burada da aynı manipülasyonu sütun kısmı için yapabiliyoruz. 1. satırın tüm elemanlarını getirdik.

array([10, 20, 30])

In [13]:
newList = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [14]:
newListMatrix = np.array(newList)

In [15]:
newListMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
newListMatrix[[0,2,4]] # Eğer liste olarak verirsek bu şekilde istediğimiz satırları alabiliriz.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [20]:
newListMatrix[[4,2,0]] # Sırası önemsiz bu şekilde de verebiliriz listeyi. # fancy indexing deniyor

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [24]:
newListMatrix[[1,2],[2,3]] # Bu şekilde 2d fancy indexingde yapabiliriz.

array([ 7, 13])