# 1. Sudoku Grid Üretme

In [21]:
import numpy as np

In [22]:
# 9x9’luk bir matris oluştur (0–9 arası)
sudoku_array = np.random.randint(1,10,81)
print(sudoku_array)

[6 7 5 3 6 9 3 5 7 2 1 2 2 9 5 9 4 6 3 9 2 6 4 3 8 6 8 5 9 4 9 7 2 8 4 6 6
 9 4 3 2 6 6 3 5 2 8 2 1 9 7 5 2 7 1 5 2 3 8 1 4 1 6 1 6 5 8 4 2 7 8 7 5 2
 1 7 2 7 6 5 5]


In [23]:
# Bazı hücreleri rastgele 0 yap (boş bırak)
indices = np.random.choice(np.arange(sudoku_array.size), replace=False,size=int(sudoku_array.size * 0.55))
sudoku_array[indices] = 0
print(sudoku_array)

[6 7 0 0 0 9 0 0 0 0 1 2 2 9 0 9 4 6 3 9 2 6 0 0 8 0 0 0 0 0 9 7 0 0 0 6 6
 0 0 3 2 0 0 3 5 0 0 0 1 9 0 0 2 0 1 0 0 0 0 1 4 1 6 1 0 0 0 4 0 7 8 0 0 0
 0 0 0 7 6 0 0]


In [24]:
sudoku_array = sudoku_array.reshape(9,9)
print(sudoku_array)

[[6 7 0 0 0 9 0 0 0]
 [0 1 2 2 9 0 9 4 6]
 [3 9 2 6 0 0 8 0 0]
 [0 0 0 9 7 0 0 0 6]
 [6 0 0 3 2 0 0 3 5]
 [0 0 0 1 9 0 0 2 0]
 [1 0 0 0 0 1 4 1 6]
 [1 0 0 0 4 0 7 8 0]
 [0 0 0 0 0 7 6 0 0]]


In [25]:
# Satır kontrolü yapan fonksiyon
def control_row(matrix):
    rows, cols = matrix.shape
    for i in range(rows):
        seen = set()
        for j in range(cols):
            val = matrix[i,j]
            if val == 0:
                continue
            if val in seen:
                new_val = np.random.randint(1,10)
                while new_val in seen:
                    new_val = np.random.randint(1,10)
                matrix[i,j] =new_val
                seen.add(new_val)
            else:
                seen.add(val)

# Sütun kontrolü yapan fonksiyon
def control_column(matrix):
    rows, cols = matrix.shape
    for i in range(cols):
        seen = set()
        for j in range(rows):
            val = matrix[j,i]
            if val == 0:
                continue
            if val in seen:
                new_val = np.random.randint(1,10)
                while new_val in seen:
                    new_val = np.random.randint(1,10)
                matrix[j,i] =new_val
                seen.add(new_val)
            else:
                seen.add(val)

In [26]:
for _ in range(5): # Geçici bir yöntem satırdan sonra sütun kontrolü yapınca bazen aynı değer gelebiliyordu. Değiştirilicek.
    control_row(sudoku_array)
    control_column(sudoku_array)
print(sudoku_array)

[[6 7 0 0 0 9 0 0 0]
 [0 1 2 5 9 0 8 4 6]
 [3 9 4 6 0 0 2 0 0]
 [0 0 0 9 7 0 0 0 4]
 [4 0 0 3 2 0 0 7 5]
 [0 0 0 1 6 0 0 2 0]
 [1 0 0 0 0 7 4 3 2]
 [9 0 0 0 4 0 7 8 0]
 [0 0 0 0 0 4 6 0 0]]


In [27]:
def control_3x3(matrix):
    rows,cols = matrix.shape
    matrix = matrix.reshape(rows*cols,1)
    seen = set()
    for i in range(rows*cols):
        if matrix[i,0] == 0:
            continue
        if matrix[i,0] in seen:
            new_val = np.random.randint(1,10)
            while new_val in seen:
                new_val = np.random.randint(1,10)
            matrix[i,0] = new_val
            seen.add(new_val)
        else:
            seen.add(matrix[i,0])
    return matrix.reshape(rows,cols)

In [29]:
for i in range(3):         
    for j in range(3):     
        block = sudoku_array[i*3:(i+1)*3, j*3:(j+1)*3]
        sudoku_array[i*3:(i+1)*3, j*3:(j+1)*3] = control_3x3(block)
        print(f"Blok ({i},{j}):")
        print(block)
        print()


Blok (0,0):
[[6 7 0]
 [0 1 2]
 [3 9 4]]

Blok (0,1):
[[0 0 9]
 [5 8 0]
 [6 0 0]]

Blok (0,2):
[[0 0 0]
 [8 4 6]
 [2 0 0]]

Blok (1,0):
[[0 0 0]
 [4 0 0]
 [0 0 0]]

Blok (1,1):
[[9 7 0]
 [3 2 0]
 [1 6 0]]

Blok (1,2):
[[0 0 4]
 [0 7 5]
 [0 2 0]]

Blok (2,0):
[[1 0 0]
 [9 0 0]
 [0 0 0]]

Blok (2,1):
[[0 0 7]
 [0 4 0]
 [0 0 9]]

Blok (2,2):
[[4 3 2]
 [7 8 0]
 [6 0 0]]



In [30]:
print(sudoku_array) # son hali

[[6 7 0 0 0 9 0 0 0]
 [0 1 2 5 8 0 8 4 6]
 [3 9 4 6 0 0 2 0 0]
 [0 0 0 9 7 0 0 0 4]
 [4 0 0 3 2 0 0 7 5]
 [0 0 0 1 6 0 0 2 0]
 [1 0 0 0 0 7 4 3 2]
 [9 0 0 0 4 0 7 8 0]
 [0 0 0 0 0 9 6 0 0]]
